---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-auto-github-proxmox-cluster
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: wego-github-proxmox-cluster
  url: ssh://git@github.com/GlenCookTech/proxmox-cluster.git

