---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: proxmox-cluster-system
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./.weave-gitops/clusters/proxmox-cluster/system
  prune: true
  sourceRef:
    kind: GitRepository
    name: wego-auto-github-proxmox-cluster

